//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.auth_page
{
    public partial class onyx_admin_register
    {
        protected global::System.Web.UI.WebControls.Label lblError;

        protected global::System.Web.UI.WebControls.Label lblSuccess;

        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        protected global::System.Web.UI.WebControls.TextBox txtUsername;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        protected global::System.Web.UI.WebControls.TextBox txtConfirm;

        protected global::System.Web.UI.WebControls.LinkButton btnRegister;
    }
}
