//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.auth_page
{
    public partial class onyx_register
    {
        protected global::System.Web.UI.WebControls.TextBox FullnameTextBox;
        protected global::System.Web.UI.WebControls.TextBox UsernameTextBox;
        protected global::System.Web.UI.WebControls.TextBox EmailTextBox;
        protected global::System.Web.UI.WebControls.TextBox PhoneTextBox;
        protected global::System.Web.UI.WebControls.TextBox DobTextBox;
        protected global::System.Web.UI.WebControls.TextBox PasswordTextBox;
        protected global::System.Web.UI.WebControls.TextBox AddressTextBox;
        protected global::System.Web.UI.WebControls.Button RegisterButton;
    }
}
