//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.auth_page
{
    public partial class onyx_resetpassword
    {
        protected global::System.Web.UI.WebControls.Panel MessagePanel;

        protected global::System.Web.UI.WebControls.Literal MessageLiteral;

        protected global::System.Web.UI.WebControls.Panel ResetFormPanel;

        protected global::System.Web.UI.WebControls.TextBox NewPasswordTextBox;

        protected global::System.Web.UI.WebControls.TextBox ConfirmPasswordTextBox;

        protected global::System.Web.UI.WebControls.Button ResetPasswordButton;
    }
}
