//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.auth_page
{
    public partial class onyx_register
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Panel pnlRegistration;
        protected global::System.Web.UI.WebControls.TextBox txtFullName;
        protected global::System.Web.UI.WebControls.TextBox txtUsername;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtPhone;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.TextBox txtDob;
        protected global::System.Web.UI.WebControls.TextBox txtAddress;
        protected global::System.Web.UI.WebControls.LinkButton btnRegister;
        protected global::System.Web.UI.WebControls.Panel pnlOtpVerification;
        protected global::System.Web.UI.WebControls.Literal litOtpDestination;
        protected global::System.Web.UI.WebControls.Label lblOtpMessage;
        protected global::System.Web.UI.WebControls.TextBox txtOtp;
        protected global::System.Web.UI.WebControls.LinkButton btnVerifyOtp;
        protected global::System.Web.UI.WebControls.LinkButton btnResendOtp;
        protected global::System.Web.UI.WebControls.LinkButton btnStartOver;
    }
}
