//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.auth_page
{
    public partial class onyx_login
    {
        protected global::System.Web.UI.WebControls.Panel MessagePanel;
        protected global::System.Web.UI.WebControls.Literal MessageLiteral;
        protected global::System.Web.UI.WebControls.Label EmailLabel;
        protected global::System.Web.UI.WebControls.TextBox EmailTextBox;
        protected global::System.Web.UI.WebControls.Label PasswordLabel;
        protected global::System.Web.UI.WebControls.TextBox PasswordTextBox;
        protected global::System.Web.UI.WebControls.Button LoginButton;
    }
}
