//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.auth_page
{
    public partial class onyx_forgotpassword
    {
        /// <summary>
        /// MessagePanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel MessagePanel;

        /// <summary>
        /// MessageLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal MessageLiteral;

        /// <summary>
        /// EmailTextBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox EmailTextBox;

        /// <summary>
        /// ResetButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button ResetButton;
    }
}
