//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.admin_page
{
    public partial class admin
    {
        /// <summary>HeadContent placeholder — for page-level CSS and scripts.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        /// <summary>Root form element.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>Log Out link button in the sidebar footer.</summary>
        protected global::System.Web.UI.WebControls.LinkButton btnLogOut;

        /// <summary>MainContent placeholder — for page body markup.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

        // ---- Sidebar Navigation Anchors (used by HighlightActiveNavLink) ----

        protected global::System.Web.UI.HtmlControls.HtmlAnchor navDashboard;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navProducts;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navProductForm;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navOrders;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navOrderDetail;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navPromos;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navUsers;
    }
}
