//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.admin_page
{
    public partial class onyx_admin_dashboard
    {
        // ---- Top Bar ----

        /// <summary>Dynamic greeting: "Good morning, onyxadmin" with Lucide hand icon.</summary>
        protected global::System.Web.UI.WebControls.Label lblGreeting;

        /// <summary>Label displaying the current date string in the greeting bar.</summary>
        protected global::System.Web.UI.WebControls.Label lblCurrentDate;

        /// <summary>Two-letter uppercase initials derived from the session username.</summary>
        protected global::System.Web.UI.WebControls.Label lblAvatar;

        // ---- Row 1: Pastel KPI Card Labels ----

        /// <summary>Today's sales total (e.g. "RM 4,785.50").</summary>
        protected global::System.Web.UI.WebControls.Label lblTodaySales;

        /// <summary>Trend annotation for today's sales vs yesterday.</summary>
        protected global::System.Web.UI.WebControls.Label lblTodaySalesTrend;

        /// <summary>Month-to-date revenue total.</summary>
        protected global::System.Web.UI.WebControls.Label lblTotalRevenue;

        /// <summary>Trend annotation for MTD revenue vs last month.</summary>
        protected global::System.Web.UI.WebControls.Label lblRevenueTrend;

        /// <summary>Month-to-date order count.</summary>
        protected global::System.Web.UI.WebControls.Label lblTotalOrders;

        /// <summary>Trend annotation for order count vs last month.</summary>
        protected global::System.Web.UI.WebControls.Label lblOrdersTrend;

        /// <summary>Average order value.</summary>
        protected global::System.Web.UI.WebControls.Label lblAOV;

        /// <summary>Trend annotation for AOV vs last month.</summary>
        protected global::System.Web.UI.WebControls.Label lblAOVTrend;

        // ---- Row 2: Dark Secondary Card Labels ----

        /// <summary>Conversion rate percentage (e.g. "3.4%").</summary>
        protected global::System.Web.UI.WebControls.Label lblConversionRate;

        /// <summary>Trend annotation for conversion rate vs last week.</summary>
        protected global::System.Web.UI.WebControls.Label lblConversionTrend;

        /// <summary>Returning customer rate percentage (e.g. "42.5%").</summary>
        protected global::System.Web.UI.WebControls.Label lblReturningRate;

        /// <summary>Count of low-stock items (e.g. "3 items").</summary>
        protected global::System.Web.UI.WebControls.Label lblLowStock;

        // ---- Row 3: Repeaters ----

        /// <summary>Repeater for the top-5 selling products leaderboard.</summary>
        protected global::System.Web.UI.WebControls.Repeater TopProductsRepeater;

        // ---- Low Stock Alerts ----

        /// <summary>Panel shown only when at least one product has stock_qty &lt; 5.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlLowStock;

        /// <summary>Repeater listing each low-stock product with name, category, and quantity.</summary>
        protected global::System.Web.UI.WebControls.Repeater LowStockRepeater;

        // ---- Row 4: Recent Orders Table ----

        /// <summary>Repeater for the recent orders activity table.</summary>
        protected global::System.Web.UI.WebControls.Repeater RecentOrdersRepeater;

        // ---- Notifications ----

        /// <summary>Repeater for the top-3 recent activity items in the notification dropdown.</summary>
        protected global::System.Web.UI.WebControls.Repeater NotifRepeater;
    }
}
