//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.admin_page
{
    public partial class onyx_admin_users
    {
        protected global::System.Web.UI.WebControls.Literal litUserCountHeader;
        protected global::System.Web.UI.WebControls.Literal litStatTotal;
        protected global::System.Web.UI.WebControls.Literal litStatAdmins;
        protected global::System.Web.UI.WebControls.Literal litStatCustomers;
        protected global::System.Web.UI.WebControls.Literal litStatRevenue;
        protected global::System.Web.UI.WebControls.Repeater UsersRepeater;
        protected global::System.Web.UI.WebControls.Literal litVisibleCount;
        protected global::System.Web.UI.WebControls.Literal litTotalCount;
        protected global::System.Web.UI.WebControls.Literal litNewThisMonth;
    }
}
