//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.admin_page
{
    public partial class onyx_admin_promos
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Literal litActiveCount;
        protected global::System.Web.UI.WebControls.Literal litRedeemedCount;
        protected global::System.Web.UI.WebControls.Literal litSavingsGiven;
        protected global::System.Web.UI.WebControls.Repeater rptVouchers;
    }
}
