//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.admin_page
{
    public partial class onyx_admin_orders
    {
        protected global::System.Web.UI.WebControls.Literal litLastUpdated;
        protected global::System.Web.UI.WebControls.Literal litStatTotal;
        protected global::System.Web.UI.WebControls.Literal litStatPending;
        protected global::System.Web.UI.WebControls.Literal litStatShipped;
        protected global::System.Web.UI.WebControls.Literal litStatDelivered;
        protected global::System.Web.UI.WebControls.Repeater OrdersRepeater;
        protected global::System.Web.UI.WebControls.Literal litOrderCount;
        protected global::System.Web.UI.WebControls.Literal litTotalRevenue;
    }
}
