//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.admin_page
{
    public partial class onyx_admin_products
    {
        protected global::System.Web.UI.WebControls.GridView ProductsGridView;
    }
}
