//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.admin_page
{
    public partial class onyx_admin_order_details
    {
        // Header
        protected global::System.Web.UI.WebControls.Literal litOrderId;
        protected global::System.Web.UI.WebControls.Literal litOrderDate;
        protected global::System.Web.UI.WebControls.Literal litCustomerNameHeader;
        protected global::System.Web.UI.WebControls.Label lblStatusBadge;

        // Customer info
        protected global::System.Web.UI.WebControls.Literal litCustName;
        protected global::System.Web.UI.WebControls.Literal litCustEmail;
        protected global::System.Web.UI.WebControls.Literal litCustPhone;
        protected global::System.Web.UI.WebControls.Literal litCustSince;

        // Shipping
        protected global::System.Web.UI.WebControls.Literal litShippingAddress;

        // Repeaters
        protected global::System.Web.UI.WebControls.Repeater OrderItemsRepeater;
        protected global::System.Web.UI.WebControls.Repeater TimelineRepeater;

        // Summary
        protected global::System.Web.UI.WebControls.Literal litSubtotal;
        protected global::System.Web.UI.WebControls.Literal litTotal;

        // Status update
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.Button btnUpdateStatus;
        protected global::System.Web.UI.WebControls.Panel pnlStatusMsg;
        protected global::System.Web.UI.WebControls.Literal litStatusMsg;

        // Metadata
        protected global::System.Web.UI.WebControls.Literal litMetaOrderId;
        protected global::System.Web.UI.WebControls.Literal litMetaDate;
        protected global::System.Web.UI.WebControls.Literal litReceiptKey;
    }
}
