//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.user_page
{
    public partial class onyx_user
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
