//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.customer_page
{
    public partial class onyx_profile
    {
        protected global::System.Web.UI.WebControls.TextBox txtSettingsFirstName;

        protected global::System.Web.UI.WebControls.TextBox txtSettingsLastName;

        protected global::System.Web.UI.WebControls.TextBox txtSettingsFullName;

        protected global::System.Web.UI.WebControls.TextBox txtSettingsEmail;

        protected global::System.Web.UI.WebControls.TextBox txtSettingsPhone;

        protected global::System.Web.UI.WebControls.TextBox txtSettingsAddress;

        protected global::System.Web.UI.WebControls.Button btnSaveSettings;

        protected global::System.Web.UI.WebControls.Label lblSettingsFeedback;
    }
}
