//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.customer_page
{
    public partial class onyx_checkout
    {
        protected global::System.Web.UI.WebControls.Content CheckoutContent;

        protected global::System.Web.UI.WebControls.Panel pnlEmptyCheckout;

        protected global::System.Web.UI.WebControls.Panel pnlCheckout;

        protected global::System.Web.UI.WebControls.Repeater rptCheckoutItems;

        protected global::System.Web.UI.WebControls.DropDownList ddlDeliveryMethod;

        protected global::System.Web.UI.WebControls.TextBox txtShippingAddress;

        protected global::System.Web.UI.WebControls.Literal litCheckoutTotal;

        protected global::System.Web.UI.WebControls.Button btnPayWithStripe;

        protected global::System.Web.UI.WebControls.Label lblCheckoutMessage;
    }
}
