//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.customer_page
{
    public partial class onyx_products
    {
        protected global::System.Web.UI.WebControls.DropDownList CategoryDropDown;
        protected global::System.Web.UI.WebControls.TextBox BrandTextBox;
        protected global::System.Web.UI.WebControls.DropDownList SortDropDown;
        protected global::System.Web.UI.WebControls.Button FilterButton;
        protected global::System.Web.UI.WebControls.Repeater ProductsRepeater;
    }
}
