//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.customer_page
{
    public partial class onyx_catalog
    {
        protected global::System.Web.UI.WebControls.Repeater FeaturedProductsRepeater;
    }
}
