//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.customer_page
{
    public partial class onyx_profile
    {
        protected global::System.Web.UI.WebControls.Literal litInitials;

        protected global::System.Web.UI.WebControls.Literal litDisplayName;

        protected global::System.Web.UI.WebControls.Literal litUsername;

        protected global::System.Web.UI.WebControls.Literal litOrderCount;

        protected global::System.Web.UI.WebControls.Literal litReviewableCount;

        protected global::System.Web.UI.WebControls.Literal litWishlistCount;

        protected global::System.Web.UI.WebControls.Literal litEmail;

        protected global::System.Web.UI.WebControls.Literal litPhone;

        protected global::System.Web.UI.WebControls.Literal litAddress;

        protected global::System.Web.UI.WebControls.Literal litMemberSince;

        protected global::System.Web.UI.WebControls.TextBox txtSettingsFullName;

        protected global::System.Web.UI.WebControls.TextBox txtSettingsEmail;

        protected global::System.Web.UI.WebControls.TextBox txtSettingsPhone;

        protected global::System.Web.UI.WebControls.TextBox txtSettingsAddress;

        protected global::System.Web.UI.WebControls.Button btnSaveSettings;

        protected global::System.Web.UI.WebControls.Label lblSettingsFeedback;

        protected global::System.Web.UI.WebControls.Panel pnlEmptyOrders;

        protected global::System.Web.UI.WebControls.Repeater rptRecentOrders;

        protected global::System.Web.UI.WebControls.Panel pnlReviewForm;

        protected global::System.Web.UI.WebControls.DropDownList ddlReviewProduct;

        protected global::System.Web.UI.WebControls.DropDownList ddlRating;

        protected global::System.Web.UI.WebControls.TextBox txtReviewComment;

        protected global::System.Web.UI.WebControls.Button btnSubmitReview;

        protected global::System.Web.UI.WebControls.Label lblReviewFeedback;

        protected global::System.Web.UI.WebControls.Panel pnlNoReviewProducts;
    }
}
