//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.customer_page
{
    public partial class onyx_invoice
    {
        protected global::System.Web.UI.WebControls.Content InvoiceContent;

        protected global::System.Web.UI.WebControls.Panel pnlInvoice;

        protected global::System.Web.UI.WebControls.Literal litCustomerName;

        protected global::System.Web.UI.WebControls.Literal litCustomerContact;

        protected global::System.Web.UI.WebControls.Literal litOrderId;

        protected global::System.Web.UI.WebControls.Literal litOrderDate;

        protected global::System.Web.UI.WebControls.Literal litShippingAddress;

        protected global::System.Web.UI.WebControls.Literal litDeliveryMethod;

        protected global::System.Web.UI.WebControls.Literal litPaymentMethod;

        protected global::System.Web.UI.WebControls.Repeater rptInvoiceItems;

        protected global::System.Web.UI.WebControls.Literal litSubtotal;

        protected global::System.Web.UI.WebControls.Panel pnlVoucherSummary;

        protected global::System.Web.UI.WebControls.Literal litVoucherLabel;

        protected global::System.Web.UI.WebControls.Literal litDiscount;

        protected global::System.Web.UI.WebControls.Literal litGrandTotal;

        protected global::System.Web.UI.WebControls.Panel pnlInvoiceError;

        protected global::System.Web.UI.WebControls.Literal litInvoiceError;
    }
}
