//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.customer_page
{
    public partial class onyx_reviews
    {
        protected global::System.Web.UI.WebControls.Panel pnlReviewForm;

        protected global::System.Web.UI.WebControls.DropDownList ddlReviewProduct;

        protected global::System.Web.UI.WebControls.DropDownList ddlRating;

        protected global::System.Web.UI.WebControls.TextBox txtReviewComment;

        protected global::System.Web.UI.WebControls.Button btnSubmitReview;

        protected global::System.Web.UI.WebControls.Label lblReviewFeedback;

        protected global::System.Web.UI.WebControls.Panel pnlNoReviewProducts;
    }
}
