//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.customer_page
{
    public partial class onyx_order_history
    {
        protected global::System.Web.UI.WebControls.Panel pnlEmptyOrders;

        protected global::System.Web.UI.WebControls.Repeater rptRecentOrders;
    }
}
