//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.customer_page
{
    public partial class onyx_checkout
    {
        protected global::System.Web.UI.WebControls.Content CheckoutContent;

        protected global::System.Web.UI.WebControls.Panel pnlEmptyCheckout;

        protected global::System.Web.UI.WebControls.Panel pnlCheckout;

        protected global::System.Web.UI.WebControls.Repeater rptCheckoutItems;

        protected global::System.Web.UI.WebControls.DropDownList ddlDeliveryMethod;

        protected global::System.Web.UI.WebControls.TextBox txtShippingAddress;

        protected global::System.Web.UI.WebControls.TextBox txtVoucherCode;

        protected global::System.Web.UI.WebControls.Button btnApplyVoucher;

        protected global::System.Web.UI.WebControls.Label lblVoucherMessage;

        protected global::System.Web.UI.WebControls.Panel pnlAppliedVoucher;

        protected global::System.Web.UI.WebControls.Literal litVoucherName;

        protected global::System.Web.UI.WebControls.Literal litVoucherCode;

        protected global::System.Web.UI.WebControls.LinkButton btnRemoveVoucher;

        protected global::System.Web.UI.WebControls.Literal litCheckoutSubtotal;

        protected global::System.Web.UI.WebControls.Panel pnlVoucherDiscount;

        protected global::System.Web.UI.WebControls.Literal litVoucherDiscount;

        protected global::System.Web.UI.WebControls.Literal litCheckoutTotal;

        protected global::System.Web.UI.WebControls.Literal litVoucherTerms;

        protected global::System.Web.UI.WebControls.Button btnPayWithStripe;

        protected global::System.Web.UI.WebControls.Label lblCheckoutMessage;
    }
}
