//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.customer_page
{
    public partial class onyx_wishlist
    {
        protected global::System.Web.UI.WebControls.Literal litWishlistCount;

        protected global::System.Web.UI.WebControls.Label lblFeedback;

        protected global::System.Web.UI.WebControls.Panel pnlEmptyWishlist;

        protected global::System.Web.UI.WebControls.Panel pnlWishlist;

        protected global::System.Web.UI.WebControls.Repeater rptWishlistItems;
    }
}
