//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONYX_DDAC.customer_page
{
    public partial class onyx_personalization
    {
        protected global::System.Web.UI.WebControls.HiddenField GamingStyleField;

        protected global::System.Web.UI.WebControls.HiddenField PreferredCategoriesField;

        protected global::System.Web.UI.WebControls.HiddenField PrioritiesField;

        protected global::System.Web.UI.WebControls.HiddenField BudgetRangeField;

        protected global::System.Web.UI.WebControls.HiddenField SetupGoalField;

        protected global::System.Web.UI.WebControls.HiddenField ComfortPreferencesField;

        protected global::System.Web.UI.WebControls.HiddenField PerformancePreferencesField;

        protected global::System.Web.UI.WebControls.HiddenField SetupConstraintsField;

        protected global::System.Web.UI.WebControls.Button BuildSetupButton;

        protected global::System.Web.UI.WebControls.Label FeedbackLabel;
    }
}
